// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    City: typeof import('./../src/views/city/index.vue')['default']
    Favour: typeof import('./../src/views/favour/index.vue')['default']
    Header: typeof import('./../src/views/home/cpns/header.vue')['default']
    Home: typeof import('./../src/views/home/index.vue')['default']
    HouseItem: typeof import('./../src/components/house-item/index.vue')['default']
    ItemV3: typeof import('./../src/components/house-item/item-v3.vue')['default']
    ItemV9: typeof import('./../src/components/house-item/item-v9.vue')['default']
    List: typeof import('./../src/views/home/cpns/list.vue')['default']
    Message: typeof import('./../src/views/message/index.vue')['default']
    Order: typeof import('./../src/views/order/index.vue')['default']
    Recommend: typeof import('./../src/views/home/cpns/recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/views/search/index.vue')['default']
    SearchBase: typeof import('./../src/views/home/cpns/search-base.vue')['default']
    SearchCity: typeof import('./../src/views/city/cpns/search-city.vue')['default']
    TabBar: typeof import('./../src/components/tabBar/index.vue')['default']
    TabCity: typeof import('./../src/views/city/cpns/tab-city.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
