// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Favour: typeof import('./../src/views/favour/index.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    Home: typeof import('./../src/views/home/index.vue')['default']
    Message: typeof import('./../src/views/message/index.vue')['default']
    Order: typeof import('./../src/views/order/index.vue')['default']
    Profile: typeof import('./../src/views/profile/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
